build: styling of output

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,7 +1,10 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo "\n🚀 Running pre-push hook..."
+# Disable automatic exit on non-zero status
+set +e
+
+echo "\n 🚀 Running pre-push hook..."
 
 echo "\n🔎  Checking for storybook changes..."
 
@@ -9,7 +12,10 @@ echo "\n🔎  Checking for storybook changes..."
 current_branch=$(git symbolic-ref --short HEAD)
 
 # Run git diff to check if any files were changed in src/modules
-git diff --name-only HEAD..origin/$current_branch | grep '^src/modules/' > /dev/null || true
+git diff --name-only --cached HEAD | grep '^src/modules/' > /dev/null || true
+
+# Re-enable automatic exit on non-zero status
+set -e
 
 # If exit status is 0, it means changes were found in src/modules
 if [ $? -eq 0 ]; then
@@ -19,9 +25,11 @@ else
   echo "\n🚀 No changes found in src/modules, skipping Storybook build."
 fi
 
-echo '\n#################
+echo '#############
 🛠️  Building for edge...
-#################'
+#############'
 
 pnpm build:for-edge
 
+
+exit 0
