build: changes pre-push commit to skip storybook builds when they aren't relevant

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,21 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm build:for-edge && pnpm build-storybook
+echo "🚀 Running pre-push hook..."
+echo "🛠️ Building for edge..."
+
+pnpm build:for-edge
+
+echo "🔎 Checking for storybook changes..."
+
+# Run git diff to check if any files were changed in src/modules
+git diff --name-only HEAD..origin/master | grep '^src/modules/' > /dev/null
+# If exit status is 0, it means changes were found in src/modules
+if [ $? -eq 0 ]; then
+  echo "🎨 Changes found in src/modules, building Storybook..."
+  npm run build-storybook
+else
+  echo "🚀 No changes found in src/modules, skipping Storybook build."
+fi
+
+
